### ISSUE TITLE
.buildozer路径可以在配置文件里指定

### ISSUE THREAD

**Issue by zx013** [nkiiiiid/kivy-apk-#3]
buildozer.spec文件的build_dir参数可以设定.buildozer的路径
build_dir = /root/.buildozer
修改成默认的值就可以不用每次都复制

**Comment by nkiiiiid** [comment]
nice大佬所言极是

**Comment by nkiiiiid** [comment]
大佬对kivy感兴趣的话欢迎入群，群号码：534622543

**Comment by zx013** [comment]
已经在群里了，前些天才加的

**Comment by nkiiiiid** [comment]
大佬多冒泡 ，可以讨论下各种骚操作
